### PR TITLE
Toby

### PR DESCRIPTION
**Pull request by TobyChen320**
Added cleaned population size dataset as well as raw dataset for population size and rental rates. Also created directories for datasets.

### CODE REVIEW

**Review by KilovoIt — APPROVED** [review]
Initial file

**Review by KilovoIt — APPROVED** [review]
reviewed and approved

**Review by KilovoIt — APPROVED** [review]

**Review by KilovoIt — APPROVED** [review]

**Review by KilovoIt — APPROVED** [review]

**Review by ilyanovak — APPROVED** [review]
reviewed and approved

**Review by ilyanovak — APPROVED** [review]
Reviewed and approved.
I recommend next time grabbing the initial data (to be cleaned) either directly from the github repo or by using relative filepaths, rather than grabbing it from a desktop file. That way anyone can replicate your actions themselves.

**Review by ilyanovak — APPROVED** [review]
looks good

**Pull request merged**
